### ISSUE TITLE
Option to show multiple banner ad on page

### ISSUE THREAD

**Issue by BeingRitam** [rdlabo/capacitor-admob#11]
Since AdMob.showBanner() can be called only once, what is the way to show ads in multiple position or switch AdPosition dynamically (Say, the viewer has reached the bottom of the page, switch the Ad on top)?
Will it be possible to call destroy and then showBanner() again with new configuration?

**Comment by rdlabo** [comment]
Currently, you cannot use multiple ads. But, you can run removeBanner() and then run showBanner() again. Thanks.
