### ISSUE TITLE
Determine banner size

### ISSUE THREAD

**Issue by bonny** [rdlabo/capacitor-admob#2]
Is it possible to add a way to determine the size of an added banner? I'm using a smart banner and the height seems to vary. Perhaps include the size in the promise returned from `showBanner()`?

The reason I want to know this is to know how much I need to position the bottom of an content area so it's not overlapping the banner (similar to the issue https://github.com/rahadur/capacitor-admob/issues/15 I think).

**Comment by rdlabo** [comment]
memo: http://hamken100.blogspot.com/2014/11/admobcocos2d-xopengl.html

**Comment by AhmedMannoun** [comment]
@bonny 
It's simple :)
use this java line to send the event

> notifyListeners("onAdSize", new JSObject().put("value", mAdView.getAdSize().getHeight()));

and receive it in ionic

>     AdMob.addListener('onAdSize', (info: any) => {
>       let AdHeight = (Number(JSON.parse(info.value))) + 'pt';
>       document.body.style.setProperty('--admob-height', AdHeight);
>       console.log('Banner Ad Height: ' + AdHeight);
>     });


check my new [comment](https://github.com/rahadur/capacitor-admob/issues/15#issuecomment-538167955).

Cheers :)
Ahmed

**Comment by bonny** [comment]
Thanks @AhmedMannoun , seems to be what I'm looking for!

**Comment by rdlabo** [comment]
@AhmedMannoun Thanks for great works!!
I add `onAdSize` Event now. We can at Swift and Java. Thanks.
