### ISSUE TITLE
AppId in 'Initialize' is not set up currectly

### ISSUE THREAD

**Issue by orirefael** [rdlabo/capacitor-admob#4]
I went to your java file and saw this line in the initialize function:
`String appId = call.getString("appId", "ca-app-pub-6564742920318187~3878397693");`

Notice that you're looking for appId property in the call you received.
In the documentation you send the appId as plain string and not wrapped with an object.
So the call of 

```
export class AppComponent {
    constructor(){
        // Initialize AdMob for your Application
        AdMob.initialize('YOUR APPID');
    }
}
```

should actually be:

```
export class AppComponent {
    constructor(){
        // Initialize AdMob for your Application
        AdMob.initialize({appId: 'YOUR APPID'});
    }
}
```

Otherwise you will take the default value there, which you claim is a sample app.
I really hope this was done unintended because otherwise people will actually show ads in their apps which actually giving money to this allegedly sample app (I honestly haven't checked if thats a sample app id or not).

Anyway, need to fix the documentation. thanks.

**Comment by rdlabo** [comment]
Thanks!! I changed document!!
