### ISSUE TITLE
iOS - Event not triggered.

### ISSUE THREAD

**Issue by orirefael** [rdlabo/capacitor-admob#6]
Hi,

I think you have a couple of issues in the iOS version.
1. rewardedAdDidDismiss should be notified the same as onRewardedVideoAdClosed IMO.
2. No event is fired at all once a video is loaded. From my testing, it seems like it happens since the delegate functions are private and not public
3. events order should be:
self.notifyListeners("onRewardedVideoCompleted", data: ["type": reward.type, "amount": reward.amount])
        self.notifyListeners("onRewarded", data: ["value": true])
        self.notifyListeners("onRewardedVideoAdClosed", data: ["value": true])

If you report onRewardedVideoAdClosed first, most clients usually deduce that video wasn't completed..

Can you confirm these issues?
Because im not getting a single event and on android everything works perfectly.

**Comment by rdlabo** [comment]
Sorry for late reply. Some fixed. Thanks.
