### ISSUE TITLE
Sample code for Ionic React

### ISSUE THREAD

**Issue by DavidFrahm** [rdlabo/capacitor-admob#7]
This plugin worked great for me in a new Ionic 5.0 React app, so I thought I'd share the web/React code for that here. Maybe this could be added to the README?

```
import React from 'react';
import { Redirect, Route } from 'react-router-dom';
import { IonApp, IonRouterOutlet, isPlatform } from '@ionic/react';
import { IonReactRouter } from '@ionic/react-router';
import Home from './pages/Home';

import { Plugins } from '@capacitor/core';
import { AdOptions, AdSize, AdPosition } from '@rdlabo/capacitor-admob';

const { AdMob } = Plugins;

const App: React.FC = () => {

  AdMob.initialize();

  const adId = {
    ios: 'ios-value-here',
    android: 'android-value-here'
  }

  const platformAdId = isPlatform('android') ? adId.android : adId.ios;

  const options: AdOptions = {
    adId: platformAdId,
    adSize: AdSize.BANNER,
    position: AdPosition.BOTTOM_CENTER,
    margin: 0,
    // isTesting: true
  }

  AdMob.showBanner(options)
    .then(
      (value) => {
        console.log("Show banner", value);  // Boolean true
      },
      (error) => {
        console.error("Show banner ERROR", error);
      }
    );

  // Subscibe Banner Event Listener
  AdMob.addListener('onAdLoaded', (info: boolean) => {
    console.log("Banner ad loaded");
  });

  // Get Banner Size
  AdMob.addListener('onAdSize', (info: boolean) => {
    console.log(info);
  });

  return (
    <IonApp>
      <IonReactRouter>
        <IonRouterOutlet>
          <Route path="/home" component={Home} exact={true} />
          <Route exact path="/" render={() => <Redirect to="/home" />} />
        </IonRouterOutlet>
      </IonReactRouter>
    </IonApp>
  );

};

export default App;
```

**Comment by jpnathan90** [comment]
@DavidFrahm when i try with above code it is throwing error 
TypeScript error in C:/projects/testApp/src/App.tsx(51,24):
[react-scripts] Cannot find name 'isPlatform'.

Please give me some suggestion

**Comment by jpnathan90** [comment]
After Adding below line I am not getting any errors
import {isPlatform } from '@ionic/react';

Can you please tell me my below questions
1. How to show this banner ad to all the pages.
2. How to add industrial ad. I need to add in particular component  or I can add the code in App.tsx file?

Please help me

**Comment by rdlabo** [comment]
@DavidFrahm Thanks for idea. This sounds good. I will create `react/README.md` tomorrow!👍

**Comment by jpnathan90** [comment]
@rdlabo can you please add other adformat integration steps (industrial and reward). I am waiting for so long

**Comment by rdlabo** [comment]
@jpnathan90 Sorry, I'm using Angular only. I can't suggest React code. Thnaks.

**Comment by kennrll18** [comment]
@DavidFrahm  I tried this in react but as soon as it gets to Admob.showBanner my app crashes. Any ideas?

**Comment by rdlabo** [comment]
@DavidFrahm Thanks for idea. I add this code to README🙏
https://github.com/rdlabo/capacitor-admob#initialize-for-ionicreact
