### ISSUE TITLE
Interstitial Ad Not Working in iOS

### ISSUE THREAD

**Issue by letsbelopez** [rdlabo/capacitor-admob#8]
Here's my error: TypeError: AdMob.prepareInterstitial is not a function. (In 'AdMob.prepareInterstitial(this.interstitialOptions)', 'AdMob.prepareInterstitial' is undefined)

I ran the same app with the same code in Android and Interstitial Ads were working fine without error.

**Comment by letsbelopez** [comment]
@rdlabo do the prepareInterstitial and the showInterstitial functions just need to be added to the Plugin.m file? I see those functions in the swift file, but they're not registered in the Plugin.m file.

**Comment by rdlabo** [comment]
Interstitial adsenses is not released. Please check README: https://github.com/rdlabo/capacitor-admob#rdlabocapacitor-admib .Thanks.

**Comment by rdlabo** [comment]
`@rdlabo/capacitor-admob@1.0.0` be implements interstitial ad🎉
