### ISSUE TITLE
Android Error: Ad size can only be set once on AdView

### ISSUE THREAD

**Issue by letsbelopez** [rdlabo/capacitor-admob#9]
Getting this error in Android:

I'm calling showBanner and hideBanner on a couple ionViewWillEnter and ionViewWillLeave functions.

```
{"arguments":["Unhandled Promise rejection:",{"message":"The ad size can only be set once on AdView."},"; Zone:","<root>","; Task:",null,"; Value:",{"message":"The ad size can only be set once on AdView."},"[undefined]"]}
```

**Comment by Paradoxu** [comment]
Same problem here, have you already found a solution?

**Comment by rdlabo** [comment]
@letsbelopez @Paradoxu `showBanner()` can use once. Please use `resumeBanner()` after hideBanner().
